config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :payments
      resources :plans
      resources :providers

      root to: "users#index"
    end
  resources :payments, only: [:index, :new, :create]
  resources :plans
  resources :providers
  devise_for :users
  root to: 'static#homepage'

  get "/residential" => "providers#residential"
  get "/business" => "providers#business"
  get "/launchyourbusiness" => "static#launchyourbusiness"
  get "/new" => "providers#new"
  get "/contact" => "static#contact"
  get "/business_landing" => "providers#business_landing"
  get "/residential_landing" => "providers#residential_landing"

  get "/business_500" => "providers#business_500"
  get "/business_1000" => "providers#business_1000"
  get "/business_2000" => "providers#business_2000"

  get "/residential_500" => "providers#residential_500"
  get "/residential_1000" =>  "providers#residential_1000"
  get "/residential_2000" => "providers#residential_2000"
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/controllers/admin/providers_controller.rb
module Admin
  class ProvidersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Provider.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Provider.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController

  def index
    @provider = Provider.all
  end

  def business
    @provider = Provider.all
  end

  def business_500
    @provider = Provider.all
  end

  def business_1000
    @provider = Provider.all
  end

  def business_2000
    @provider = Provider.all
  end

  def residential
    @provider = Provider.all
  end

  def residential_500
    @provider = Provider.all
  end

  def residential_1000
    @provider = Provider.all
  end

  def residential_2000
    @provider = Provider.all
  end

  def create
    @provider = Provider.create(params.required(:provider).permit(:name, :user_id, :price, :e_plan,
                                                                   :energy_price, :average_rate, :average_e_rate,
                                                                   :low_rate, :med_rate, :high_rate,
                                                                   :base_charge, :term, :term_fee))

    @provider.user_id = current_user.id

    if @provider.save!
      redirect_to @provider
    else
      render :new
    end
  end

  def new
   @provider = Provider.new
  end

  def show
    @provider = Provider.find(params[:id])

    @plan = Plan.new
    @payment = Payment.new
  end

end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/business.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Business Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", business_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", business_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", business_2000_path %>
  </div>
</div>

app/views/providers/business_1000.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Business Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", business_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", business_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", business_2000_path %>
  </div>
  <% @provider.in_groups_of(3, false).each do |group| %>
    <div class='row'>
      <% group.each do |p| %>
        <div class='col-md-3 prov-box'>
          <div class="prov-header-box">
            <h3 class="text-center prov-name">
              <%= link_to p.name %>
            </h3>
          </div>
          <h3 class="text-center prov-price">
            <%= p.med_rate %><small> /kWh</small>
          </h3>
          <p class="text-center">
            <%= p.description %>
          </p>
          <div class="prov-term">
            <p class="text-center">
              <%= p.term %> Term
            </p>
          </div>
          <div class="prov-btn-box">
            <%= link_to "Select", provider_path(p), :class => "prov-button text-center" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/providers/business_2000.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Business Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", business_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", business_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", business_2000_path %>
  </div>
  <% @provider.in_groups_of(3, false).each do |group| %>
    <div class='row'>
      <% group.each do |p| %>
        <div class='col-md-3 prov-box'>
          <div class="prov-header-box">
            <h3 class="text-center prov-name">
              <%= link_to p.name %>
            </h3>
          </div>
          <h3 class="text-center prov-price">
            <%= p.high_rate %><small> /kWh</small>
          </h3>
          <p class="text-center">
            <%= p.description %>
          </p>
          <div class="prov-term">
            <p class="text-center">
              <%= p.term %> Term
            </p>
          </div>
          <div class="prov-btn-box">
            <%= link_to "Select", provider_path(p), :class => "prov-button text-center" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/providers/business_500.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Business Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", business_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", business_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", business_2000_path %>
  </div>
  <% @provider.in_groups_of(3, false).each do |group| %>
    <div class='row'>
      <% group.each do |p| %>
        <div class='col-md-3 prov-box'>
          <div class="prov-header-box">
            <h3 class="text-center prov-name">
              <%= link_to p.name %>
            </h3>
          </div>
          <h3 class="text-center prov-price">
            <%= p.low_rate %><small> /kWh</small>
          </h3>
          <p class="text-center">
            <%= p.description %>
          </p>
          <div class="prov-term">
            <p class="text-center">
              <%= p.term %> Term
            </p>
          </div>
          <div class="prov-btn-box">
            <%= link_to "Select", provider_path(p), :class => "prov-button text-center" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/providers/business_landing.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <%= image_tag "amos8.jpg" %>
    </div>
    <div class="col-xs-6 busi-button">
      <%= link_to "Select a Plan", business_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6">

    </div>
    <div class="col-xs-6">
      <%= image_tag "workphoto.jpg" %>
    </div>
  </div>
</div>

app/views/providers/index.html.erb
<% @provider.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |p| %>
      <div class='col-md-3'>
        <h3 class="text-center">
          <%= link_to p.name %>
        </h3>
        <p class="text-center">
          <%= p.price %>
        </p>
        <p class="text-center">
          <%= p.term %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/providers/new.html.erb
<div class="container new-provider">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <h1>
        Add a New Provider
      </h1>

      <div class="well">
        <%= bootstrap_form_for(@provider, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
        <%= f.text_field :name %>
        <%= f.text_field :price %>
        <%= f.check_box :e_plan %>
        <%= f.text_field :energy_price %>
        <%= f.text_field :average_rate %>
        <%= f.text_field :average_e_rate %>
        <%= f.text_field :low_rate %>
        <%= f.text_field :med_rate %>
        <%= f.text_field :high_rate %>
        <%= f.text_field :base_charge %>
        <%= f.text_field :term %>
        <%= f.text_field :term_fee %>
        <div class="new-store-btn">
          <button type="submit" class="btn btn-primary">
            Submit
          </button>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/providers/residential.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Residential Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", residential_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", residential_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", residential_2000_path %>
  </div>
</div>

app/views/providers/residential_1000.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Residential Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", residential_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", residential_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", residential_2000_path %>
  </div>
  <% @provider.in_groups_of(3, false).each do |group| %>
    <div class='row'>
      <% group.each do |p| %>
        <div class='col-md-3 prov-box'>
          <div class="prov-header-box">
            <h3 class="text-center prov-name">
              <%= link_to p.name %>
            </h3>
          </div>
          <h3 class="text-center prov-price">
            <%= p.med_rate %><small> /kWh</small>
          </h3>
          <p class="text-center">
            <%= p.description %>
          </p>
          <div class="prov-term">
            <p class="text-center">
              <%= p.term %> Term
            </p>
          </div>
          <div class="prov-btn-box">
            <%= link_to "Select", provider_path(p), :class => "prov-button text-center" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/providers/residential_2000.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Residential Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", residential_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", residential_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", residential_2000_path %>
  </div>
  <% @provider.in_groups_of(3, false).each do |group| %>
    <div class='row'>
      <% group.each do |p| %>
        <div class='col-md-3 prov-box'>
          <div class="prov-header-box">
            <h3 class="text-center prov-name">
              <%= link_to p.name %>
            </h3>
          </div>
          <h3 class="text-center prov-price">
            <%= p.high_rate %><small> /kWh</small>
          </h3>
          <p class="text-center">
            <%= p.description %>
          </p>
          <div class="prov-term">
            <p class="text-center">
              <%= p.term %> Term
            </p>
          </div>
          <div class="prov-btn-box">
            <%= link_to "Select", provider_path(p), :class => "prov-button text-center" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/providers/residential_500.html.erb
<div class="container">
  <h1 class="text-center res-prov-head"> Residential Energy</h1>

  <div class="col-xs-4 tier-buttons text-center">
    <%= link_to "500 kWh", residential_500_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "1000 kWh", residential_1000_path %>
  </div>
  <div class="col-xs-4  tier-buttons text-center">
    <%= link_to "2000 kWh", residential_2000_path %>
  </div>
  <% @provider.in_groups_of(3, false).each do |group| %>
    <div class='row'>
      <% group.each do |p| %>
        <div class='col-md-3 prov-box'>
          <div class="prov-header-box">
            <h3 class="text-center prov-name">
              <%= link_to p.name %>
            </h3>
          </div>
          <h3 class="text-center prov-price">
            <%= p.low_rate %><small> /kWh</small>
          </h3>
          <p class="text-center">
            <%= p.description %>
          </p>
          <div class="prov-term">
            <p class="text-center">
              <%= p.term %> Term
            </p>
          </div>
          <div class="prov-btn-box">
            <%= link_to "Select", provider_path(p), :class => "prov-button text-center" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/providers/residential_landing.html.erb
<section class="business-sec">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="single-business" p style="color:DodgerBlue"p>
        <h3>Starting a new service?</h3>
        </p></h3>
        <p>Start enjoying the freedom that comes from low energy rates.  Choose Amos Energy.</p> </p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="single-business"p style="color:DodgerBlue"p>
      <h3>Switch to Amos Energy</h3>
      </p> </h3>
      <p> When last did you check your energy rates? Amos energy makes it easy for you to switch. click on sign up page and the rest is easy.</p> </p>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="single-business"p style="color:DodgerBlue"p>
    <h3>Moving to a new location?</h3>
    </p></h3>
    <p> With so much on your to do lists, relax and  Let Amos Energy handle your new service at yoour new location while you focus on moving. Give us a call or sign up online</p>
  </div>
  </div>
  </div>
  </div>
</section>

</div>
</div>
</section>
<section class="boxes_area">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="box">
          <h3></h3>
          <p></p>
          <i class=""></i>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="box">
          <h3></h3>
          <p> </p>
          <i class=""></i>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="box">
          <h3></h3>
          <p> </p>
          <i class=""></i>
        </div>
      </div>
    </div>
  </div>
</section>




</div>
</div>


<%= link_to "Select a Plan", residential_path, :class => "res-button" %>

<section class="extra-section">
  <div class="container">
    <div class="row">
      <!-- Mission Text -->
      <div class="col-sm-12 text-center">
        <h2 class="section-title text-center"> Residential Energy</h2>
        <p>God said, " Let there be light", and there was light. </p>
      </div>
    </div>
  </div>
</section>
<!-- Unique Section Ends Here -->

<!-- Moving Section Goes Here -->
<section class="moving-section services section-top no-mt" id="services">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2 class="section-title text-center">Amos Energy makes moving easy.</h2>
      </div>

      <!-- Moving Text -->
      <div class="col-sm-12">
        <div class="single-services text-center">
          <p></p>
        </div>
      </div>
    </div>
  </div>
  <div class="">
    <div class="container">
      <div class="col-md-12">
      </div>
      </form>
    </div>
  </div>
  </div>
  </div>
  </div>
  </div>
  </div>
</section>

app/views/providers/show.html.erb
<div class="container">
  <div class="row">
    <div class="show-header text-center">
      <h1>
        <%= @provider.name %>
      </h1>
    </div>
    <div class="show-body">
      <div class="col-md-6 show-price text-center">
        <h3>
          Average Price:
        </h3>
        <p>
          <%= @provider.price %>
        </p>
      </div>
      <div class="col-md-6 show-price text-center">
        <h3>
          Energy Price:
        </h3>
        <p>
          <%= @provider.energy_price %>
        </p>
      </div>
    </div>
      <h3 class="text-center"><b>
        Price based on usage:
      </b></h3>
      <div class="col-md-4 show-tiers text-center">
        <p>
          0-800 kWh: <b><%= @provider.low_rate %></b> /kWh
        </p>
      </div>
      <div class="col-md-4 show-tiers text-center">
        <p>
          801-1200 kWh: <b><%= @provider.med_rate %></b> /kWh
        </p>
      </div>
      <div class="col-md-4 show-tiers text-center">
        <p>
          >1200 kWh: <b><%= @provider.high_rate %></b> /kWh
        </p>
      </div>
      <p class="text-center show-base">
        Base Charge: <%= @provider.base_charge %>
      </p>
      <p class="text-center">
        Term length of <%= @provider.term %>, with a <%= @provider.term_fee %> early termination fee
      </p>
  </div>
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
            Sign Up</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <div class="row">
          <%= render 'plans/plan' %>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
            Confirm Plan</a>
        </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse">
        <div class="row">
          <div class="col-xs-10 col-xs-offset-1">
            <h1>
              <%= @provider.name %>
            </h1>

            <div class="well">
              <%= bootstrap_form_for(@plan) do |f| %>
                <% f.hidden_field :provider_id, :value => @provider.id %>
                <% f.hidden_field :term_length, :value => @provider.term %>

                <%= f.text_field :esi_id, label: "ESI ID" %>

                <%= f.text_field :veterans, label: "Energy Credits for Veterans"%>

                <%= f.text_field :cert, label: "Certificat No." %>

                <%= f.select :term, [["24 Months"],["12 Months"],["6 Months"],["3 Months"]] %>

                <%= f.select :service_type, [["Residential"],["Commercial"]] %>

                <%= f.select :energy_type, [["Electricity"],["Electricity and Gas"],["Gas"]] %>

                <%= f.text_field :consultant_id, label: "Your Consultant ID" %>

                <%= f.check_box :terms, label: "I agree to the Terms of Service" %>

                <button type="submit" class="btn btn-primary">
                  Purchase
                </button>
              <% end %>
            </div>
          </div>
      </div>
    </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
            Payment</a>
        </h4>
      </div>
      <div id="collapse3" class="panel-collapse collapse">
        <div class="row">
          <div class="col-xs-10 col-xs-offset-1">
            <h1>New Payment</h1>

            <% if @payment.errors.any? %>
              <div class="alert alert-danger">
                <ul>
                  <% @payment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="well">
              <%= bootstrap_form_for @payment do |f| %>
                <%= f.text_field :first_name, class: "form-control" %>

                <%= f.text_field :last_name,class: "form-control" %>

                <%= f.text_field :credit_card_number, class: "form-control" %>

                <%= f.select :expiration_month, months, {}, class: "form-control" %>

                <%= f.select :expiration_year, years, {}, class: "form-control" %>

                <%= f.text_field :card_security_code, class: "form-control" %>

                <%= f.number_field :amount, class: "form-control", step: "0.01" %>
                <div class="form-group">
                  <%= f.submit "Charge Credit Card", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  </div>
</div>

app/views/providers/sign_up.html.erb
<%= @provider.inspect %>