config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :payments
      resources :plans
      resources :providers

      root to: "users#index"
    end
  resources :payments, only: [:index, :new, :create]
  resources :plans
  resources :providers
  devise_for :users
  root to: 'static#homepage'

  get "/residential" => "providers#residential"
  get "/business" => "providers#business"
  get "/launchyourbusiness" => "static#launchyourbusiness"
  get "/new" => "providers#new"
  get "/contact" => "static#contact"
  get "/business_landing" => "providers#business_landing"
  get "/residential_landing" => "providers#residential_landing"

  get "/business_500" => "providers#business_500"
  get "/business_1000" => "providers#business_1000"
  get "/business_2000" => "providers#business_2000"

  get "/residential_500" => "providers#residential_500"
  get "/residential_1000" =>  "providers#residential_1000"
  get "/residential_2000" => "providers#residential_2000"
end

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-6">

      </div>

      <div class="col-md-2 col-sm-3 col-xs-3">

      </div>
      <div class="col-md-2 col-sm-6 col-xs-6">
        <h6>Phone numbers:</h6>

        <p>1(800)335-9956 <br></p>
      </div>
      <div class="col-md-2 col-sm-3 col-xs-3">
        <h6>follow us</h6>
        <a href="">
          <p>twitter</p>
        </a>
        <a href="">
          <p>instragram</p>
        </a>
        <a href="">
          <p>linkedin</p>
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class="header-top">
  <div class="container">
    <div class="col-md-4">
      <div class="logo">
        <a href="index.html"><img src="assets/images/home-page/logo.png" alt=""></a>
      </div>
    </div>
    <div class="col-md-8 text-right">
      <div class="top-menu">
        <div class="top-top-menu">
          <a href="http://amosenergy.net/"> <i class="fa fa-envelope"></i> info@amosenergy.net</a>
          <a href="#">Pay bills</a>
          <a href="#">Launch your own business</a>
        </div>
        <div class="top-bottom-menu">
          <a>call 1(877)266-7729</a>
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-google-plus"></i></a>
          <a href="#"><i class="fa fa-youtube"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

<nav class="bottom navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-image">
          <%= link_to image_tag('logo.png'), root_path %>
        </li>
        <li class="nav-link"><%= link_to 'Residential Energy', residential_landing_path %></li>
        <li class="nav-link"><%= link_to 'Business Energy', business_landing_path %></li>
        <li class="nav-link"><%= link_to 'Contact', contact_path %></li>
        <% if user_signed_in? %>
          <% if current_user.user_type == 'admin' %>
            <li class="nav-link">
              <%= link_to "Admin Dashboard", admin_root_path %>
            </li>
            <li class="nav-link">
              <%= link_to 'Add Provider', new_provider_path %>
            </li>
          <% end %>
          <% end %>
      </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="nav-link-grn"><%= link_to('My Account', edit_user_registration_path) %></li>
            <li class="nav-link-grn"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li class="nav-link-grn"><%= link_to('Sign in', new_user_session_path)%></li>
            <li class="nav-link-grn"><%= link_to('Sign up', new_user_registration_path) %></li>
          <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>