config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :payments
      resources :plans
      resources :providers

      root to: "users#index"
    end
  resources :payments, only: [:index, :new, :create]
  resources :plans
  resources :providers
  devise_for :users
  root to: 'static#homepage'

  get "/residential" => "providers#residential"
  get "/business" => "providers#business"
  get "/launchyourbusiness" => "static#launchyourbusiness"
  get "/new" => "providers#new"
  get "/contact" => "static#contact"
  get "/business_landing" => "providers#business_landing"
  get "/residential_landing" => "providers#residential_landing"

  get "/business_500" => "providers#business_500"
  get "/business_1000" => "providers#business_1000"
  get "/business_2000" => "providers#business_2000"

  get "/residential_500" => "providers#residential_500"
  get "/residential_1000" =>  "providers#residential_1000"
  get "/residential_2000" => "providers#residential_2000"
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/controllers/admin/plans_controller.rb
module Admin
  class PlansController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Plan.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Plan.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController


  def plan

  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(params.required(:plan).permit(:user_id, :provider_id, :term_length, :esi_id, :veterans, :cert,
                                                   :term, :service_type, :energy_type, :consultant_id, :terms))

    @plan.user_id = current_user.id

    if @plan.save!
      redirect_to root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_new.html.erb
<%= bootstrap_form_for(@plan, html: { class: 'form-inline' }) do |f| %>
  <% f.hidden_field :provider_id, :value => @provider.id %>
  <% f.hidden_field :term_length, :value => @provider.term %>

  <button type="submit" class="btn btn-primary">
    Purchase
  </button>
<% end %>

app/views/plans/_plan.html.erb
    <div class="col-xs-5 col-xs-offset-1">
      <h1>Sign In</h1>
        <div class="well">
          <%= bootstrap_form_for(:user, :url => session_path(:user)) do |f| %>
            <%= f.text_field :email %>
            <%= f.password_field :password %>
            <%= f.check_box :remember_me %>
            <%= f.submit 'Sign in' %>
            <%= link_to "Forgot your password?", new_password_path(:user) %>
          <% end %>
        </div>
      </div>
    <div class="col-xs-5">
        <h1>Sign Up</h1>
        <div class="well">
      <%= bootstrap_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= render "devise/shared/error_messages", resource: resource %>

        <%= f.email_field :email %>

        <%= f.text_field :first_name %>

        <%= f.text_field :last_name %>

        <%= f.text_field :address %>

        <%= f.text_field :city %>

        <%= f.text_field :state %>

        <%= f.text_field :zip %>

        <%= f.text_field :phone_number %>

        <%= f.text_field :mobile_number %>

        <%= f.text_field :work_number %>

        <%= f.text_field :mailing_address %>

        <%= f.text_field :mailing_city %>

        <%= f.text_field :mailing_state %>

        <%= f.text_field :mailing_zip %>

        <%= f.date_field :birthdate %>

        <%= f.text_field :license, label: "Last 4 digits of License" %>

        <%= f.select :language, [["English"], ["Spanish"]] %>

        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= f.password_field :password, autocomplete: "new-password" %>

        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>

        <div class="actions">
          <%= f.submit "Sign up" %>
        </div>
      <% end %>

    </div>
  </div>
</div>